steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/data-shark-378612/nft_price_prediction:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/data-shark-378612/nft_price_prediction:$SHORT_SHA']
